// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.20.0
// source: userserver/api/proto/rpc/code.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// @plugins=protoc-gen-go-errors
type ERR int32

const (
	ERR_OK                ERR = 0      // OK
	ERR_CLIENT_ERROR      ERR = 100000 // Client's Side Error
	ERR_INVALID_PARAMS    ERR = 100001 // Invalid Parameters
	ERR_CANCELLED         ERR = 100002 // Cancelled
	ERR_SERVER_ERROR      ERR = 200000 //Server's Side Error
	ERR_RESOURCES_TIMEOUT ERR = 200001 //get resources timeout
	ERR_IMPLEMENTED       ERR = 200002 //Implemented
)

// Enum value maps for ERR.
var (
	ERR_name = map[int32]string{
		0:      "OK",
		100000: "CLIENT_ERROR",
		100001: "INVALID_PARAMS",
		100002: "CANCELLED",
		200000: "SERVER_ERROR",
		200001: "RESOURCES_TIMEOUT",
		200002: "IMPLEMENTED",
	}
	ERR_value = map[string]int32{
		"OK":                0,
		"CLIENT_ERROR":      100000,
		"INVALID_PARAMS":    100001,
		"CANCELLED":         100002,
		"SERVER_ERROR":      200000,
		"RESOURCES_TIMEOUT": 200001,
		"IMPLEMENTED":       200002,
	}
)

func (x ERR) Enum() *ERR {
	p := new(ERR)
	*p = x
	return p
}

func (x ERR) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ERR) Descriptor() protoreflect.EnumDescriptor {
	return file_userserver_api_proto_rpc_code_proto_enumTypes[0].Descriptor()
}

func (ERR) Type() protoreflect.EnumType {
	return &file_userserver_api_proto_rpc_code_proto_enumTypes[0]
}

func (x ERR) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ERR.Descriptor instead.
func (ERR) EnumDescriptor() ([]byte, []int) {
	return file_userserver_api_proto_rpc_code_proto_rawDescGZIP(), []int{0}
}

var File_userserver_api_proto_rpc_code_proto protoreflect.FileDescriptor

var file_userserver_api_proto_rpc_code_proto_rawDesc = []byte{
	0x0a, 0x23, 0x75, 0x73, 0x65, 0x72, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x70, 0x63, 0x2f, 0x63, 0x6f, 0x64, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x72, 0x70, 0x63, 0x2a, 0x88, 0x01, 0x0a, 0x03, 0x45,
	0x52, 0x52, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x4b, 0x10, 0x00, 0x12, 0x12, 0x0a, 0x0c, 0x43, 0x4c,
	0x49, 0x45, 0x4e, 0x54, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0xa0, 0x8d, 0x06, 0x12, 0x14,
	0x0a, 0x0e, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x5f, 0x50, 0x41, 0x52, 0x41, 0x4d, 0x53,
	0x10, 0xa1, 0x8d, 0x06, 0x12, 0x0f, 0x0a, 0x09, 0x43, 0x41, 0x4e, 0x43, 0x45, 0x4c, 0x4c, 0x45,
	0x44, 0x10, 0xa2, 0x8d, 0x06, 0x12, 0x12, 0x0a, 0x0c, 0x53, 0x45, 0x52, 0x56, 0x45, 0x52, 0x5f,
	0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0xc0, 0x9a, 0x0c, 0x12, 0x17, 0x0a, 0x11, 0x52, 0x45, 0x53,
	0x4f, 0x55, 0x52, 0x43, 0x45, 0x53, 0x5f, 0x54, 0x49, 0x4d, 0x45, 0x4f, 0x55, 0x54, 0x10, 0xc1,
	0x9a, 0x0c, 0x12, 0x11, 0x0a, 0x0b, 0x49, 0x4d, 0x50, 0x4c, 0x45, 0x4d, 0x45, 0x4e, 0x54, 0x45,
	0x44, 0x10, 0xc2, 0x9a, 0x0c, 0x42, 0x1b, 0x5a, 0x19, 0x75, 0x73, 0x65, 0x72, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x70,
	0x63, 0x3b, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_userserver_api_proto_rpc_code_proto_rawDescOnce sync.Once
	file_userserver_api_proto_rpc_code_proto_rawDescData = file_userserver_api_proto_rpc_code_proto_rawDesc
)

func file_userserver_api_proto_rpc_code_proto_rawDescGZIP() []byte {
	file_userserver_api_proto_rpc_code_proto_rawDescOnce.Do(func() {
		file_userserver_api_proto_rpc_code_proto_rawDescData = protoimpl.X.CompressGZIP(file_userserver_api_proto_rpc_code_proto_rawDescData)
	})
	return file_userserver_api_proto_rpc_code_proto_rawDescData
}

var file_userserver_api_proto_rpc_code_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_userserver_api_proto_rpc_code_proto_goTypes = []interface{}{
	(ERR)(0), // 0: rpc.ERR
}
var file_userserver_api_proto_rpc_code_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_userserver_api_proto_rpc_code_proto_init() }
func file_userserver_api_proto_rpc_code_proto_init() {
	if File_userserver_api_proto_rpc_code_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_userserver_api_proto_rpc_code_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_userserver_api_proto_rpc_code_proto_goTypes,
		DependencyIndexes: file_userserver_api_proto_rpc_code_proto_depIdxs,
		EnumInfos:         file_userserver_api_proto_rpc_code_proto_enumTypes,
	}.Build()
	File_userserver_api_proto_rpc_code_proto = out.File
	file_userserver_api_proto_rpc_code_proto_rawDesc = nil
	file_userserver_api_proto_rpc_code_proto_goTypes = nil
	file_userserver_api_proto_rpc_code_proto_depIdxs = nil
}
